In [ ]:
# Importing libraries
import nltk
import time
import random
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
 
# download the treebank corpus from nltk
nltk.download('treebank')
 
# download the universal tagset from nltk
nltk.download('universal_tagset')
 
# reading the Treebank tagged sentences
nltk_data = list(nltk.corpus.treebank.tagged_sents(tagset='universal'))
 
# print the first two sentences along with tags
print(nltk_data[:2])

[nltk_data] Downloading package treebank to /root/nltk_data...
[nltk_data]   Package treebank is already up-to-date!
[nltk_data] Downloading package universal_tagset to /root/nltk_data...
[nltk_data]   Package universal_tagset is already up-to-date!


[[('Pierre', 'NOUN'), ('Vinken', 'NOUN'), (',', '.'), ('61', 'NUM'), ('years', 'NOUN'), ('old', 'ADJ'), (',', '.'), ('will', 'VERB'), ('join', 'VERB'), ('the', 'DET'), ('board', 'NOUN'), ('as', 'ADP'), ('a', 'DET'), ('nonexecutive', 'ADJ'), ('director', 'NOUN'), ('Nov.', 'NOUN'), ('29', 'NUM'), ('.', '.')], [('Mr.', 'NOUN'), ('Vinken', 'NOUN'), ('is', 'VERB'), ('chairman', 'NOUN'), ('of', 'ADP'), ('Elsevier', 'NOUN'), ('N.V.', 'NOUN'), (',', '.'), ('the', 'DET'), ('Dutch', 'NOUN'), ('publishing', 'VERB'), ('group', 'NOUN'), ('.', '.')]]


In [ ]:
# print each word with its respective tag for first two sentences
for sent in nltk_data[:2]:
    print('==============')
    for tuple in sent:
        print(tuple,)

('Pierre', 'NOUN')
('Vinken', 'NOUN')
(',', '.')
('61', 'NUM')
('years', 'NOUN')
('old', 'ADJ')
(',', '.')
('will', 'VERB')
('join', 'VERB')
('the', 'DET')
('board', 'NOUN')
('as', 'ADP')
('a', 'DET')
('nonexecutive', 'ADJ')
('director', 'NOUN')
('Nov.', 'NOUN')
('29', 'NUM')
('.', '.')
('Mr.', 'NOUN')
('Vinken', 'NOUN')
('is', 'VERB')
('chairman', 'NOUN')
('of', 'ADP')
('Elsevier', 'NOUN')
('N.V.', 'NOUN')
(',', '.')
('the', 'DET')
('Dutch', 'NOUN')
('publishing', 'VERB')
('group', 'NOUN')
('.', '.')


In [ ]:
# split data into training and validation set in the ratio 80:20
train_set, test_set = train_test_split(nltk_data, train_size = 0.80, test_size = 0.20, random_state = 101)

In [ ]:
# create list of train and test tagged words
train_tagged_words = [ tup for sent in train_set for tup in sent ]
test_tagged_words = [ tup for sent in test_set for tup in sent ]
print(len(train_tagged_words))
print(len(test_tagged_words))

80310
20366


In [ ]:
# check some of the tagged words.
train_tagged_words[:5]

[('Drink', 'NOUN'),
 ('Carrier', 'NOUN'),
 ('Competes', 'VERB'),
 ('With', 'ADP'),
 ('Cartons', 'NOUN')]

In [ ]:
# use set datatype to check how many unique tags are present in training data
tags = {tag for word, tag in train_tagged_words}
print('Number of tags:', len(tags))
print(tags)
 
# check total words in vocabulary
vocab = {word for word, tag in train_tagged_words}
print('Number of words in vocabulary:', len(vocab))

Number of tags: 12
{'.', 'DET', 'VERB', 'NOUN', 'ADV', 'NUM', 'CONJ', 'ADJ', 'ADP', 'X', 'PRON', 'PRT'}
Number of words in vocabulary: 11052


In [ ]:
#Creating encoding dictionaries
encode_hs = {}
decode_hs = {}
for idx, t in enumerate(tags):
    encode_hs[t] = idx
    decode_hs[idx] = t
print("Encode: \n", encode_hs)
print("Decode: \n", decode_hs)

Encode: 
 {'.': 0, 'DET': 1, 'VERB': 2, 'NOUN': 3, 'ADV': 4, 'NUM': 5, 'CONJ': 6, 'ADJ': 7, 'ADP': 8, 'X': 9, 'PRON': 10, 'PRT': 11}
Decode: 
 {0: '.', 1: 'DET', 2: 'VERB', 3: 'NOUN', 4: 'ADV', 5: 'NUM', 6: 'CONJ', 7: 'ADJ', 8: 'ADP', 9: 'X', 10: 'PRON', 11: 'PRT'}


In [ ]:
#Encoding for Visible States
encode_vs = {}
for v,k in enumerate(vocab):
    encode_vs[k] = v
encode_vs

{'negotiator': 0,
 'belts': 1,
 'galvanized': 2,
 'certain': 3,
 'Urban': 4,
 'ships': 5,
 'Services': 6,
 'intelligence': 7,
 'responses': 8,
 'short-term': 9,
 'entrenched': 10,
 'longest': 11,
 'ABA': 12,
 'Daniel': 13,
 'influenced': 14,
 'Moreover': 15,
 'Ichiro': 16,
 'Firms': 17,
 'Neanderthals': 18,
 'Literacy': 19,
 'B': 20,
 '*T*-53': 21,
 'apparent': 22,
 '494.50': 23,
 'Only': 24,
 'begun': 25,
 'town': 26,
 '*ICH*-1': 27,
 "'re": 28,
 'speed': 29,
 'Craftsmen': 30,
 'purchasers': 31,
 'flagrant': 32,
 'career': 33,
 'speculative': 34,
 'pursued': 35,
 'acquisitions': 36,
 'Soldado': 37,
 'Louisiana-Pacific': 38,
 'unveiled': 39,
 'Illinois': 40,
 'single-handed': 41,
 'feels': 42,
 'certificates': 43,
 'LANDOR': 44,
 'failing': 45,
 'refused': 46,
 'linked': 47,
 '7\\/16': 48,
 'Nippon': 49,
 'teaching': 50,
 'Cluff': 51,
 'stimulated': 52,
 'emergencies': 53,
 'alienated': 54,
 'articles': 55,
 'perpetual': 56,
 'Ann': 57,
 '71': 58,
 'possessions': 59,
 'agree': 60,
 'pr

In [ ]:
#Computing pi
#Going with first word of each sentence
pi = np.zeros(len(encode_hs))
for sentence in train_set:
    word, t = sentence[0]
    pi[encode_hs[t]]+=1
print(pi)

[248. 724.  34. 903. 165.  26. 166. 132. 417.  66. 245.   5.]


In [ ]:
#Computing A
A = np.zeros((len(encode_hs), len(encode_hs)), dtype = np.float128)

for sentence in train_set:
    for i in range(1,len(sentence)):
        #Taking the second element of the tuple
        t = sentence[i][1]
        prev_t = sentence[i-1][1]
        A[encode_hs[prev_t], encode_hs[t]] += 1

A = A/np.reshape(np.sum(A, axis=1), (-1,1))

pd.DataFrame(A, index = encode_hs.keys(), columns = encode_hs.keys())

.       DET      VERB      NOUN       ADV       NUM      CONJ  \
.     0.099163  0.142788  0.129105  0.183677  0.052318  0.113168  0.063748   
DET   0.017395  0.005894  0.040253  0.635998  0.012076  0.022858  0.000431   
VERB  0.034807  0.133610  0.167956  0.110589  0.083886  0.022836  0.005433   
NOUN  0.240153  0.012984  0.149224  0.262330  0.016905  0.009150  0.042436   
ADV   0.139309  0.071013  0.339154  0.032208  0.081490  0.029880  0.006985   
NUM   0.118971  0.003573  0.020722  0.351554  0.003573  0.184352  0.014291   
CONJ  0.035126  0.123491  0.150384  0.349067  0.057080  0.040615  0.000549   
ADJ   0.066019  0.005243  0.011456  0.696893  0.005243  0.021748  0.016893   
ADP   0.038739  0.321053  0.008482  0.323585  0.014559  0.063299  0.000886   
X     0.160900  0.056709  0.206459  0.061707  0.025759  0.003076  0.010381   
PRON  0.041913  0.009567  0.484738  0.212756  0.036902  0.006834  0.005011   
PRT   0.045010  0.101370  0.401174  0.250489  0.009393  0.056751  0.002348   

           ADJ       ADP         X      PRON       PRT  
.     0.048133  0.072601  0.027849  0.064070  0.003381  
DET   0.206440  0.009919  0.045141  0.003306  0.000288  
VERB  0.066390  0.092357  0.215930  0.035543  0.030663  
NOUN  0.012548  0.176847  0.028843  0.004618  0.043961  
ADV   0.130772  0.119519  0.022895  0.012029  0.014746  
NUM   0.035370  0.037513  0.202572  0.001429  0.026081  
CONJ  0.113611  0.055982  0.009330  0.060373  0.004391  
ADJ   0.063301  0.080583  0.020971  0.000194  0.011456  
ADP   0.107102  0.016964  0.034561  0.069502  0.001266  
X     0.017686  0.142253  0.075740  0.054210  0.185121  
PRON  0.070615  0.022323  0.088383  0.006834  0.014123  
PRT   0.082975  0.019569  0.012133  0.017613  0.001174

In [ ]:
#Computing B
B = np.empty((len(encode_hs), len(encode_vs)), dtype = np.float128)
B[:,:] = 0
for sentence in train_set:
    for word, t in sentence:
        B[encode_hs[t], encode_vs[word]] += 1

B=B/np.reshape(np.sum(B, axis=1), (-1,1))
print(pd.DataFrame(B, index = encode_hs.keys(), columns = encode_vs.keys()))

      negotiator     belts  galvanized   certain     Urban     ships  \
.       0.000000  0.000000    0.000000  0.000000  0.000000  0.000000   
DET     0.000000  0.000000    0.000000  0.000000  0.000000  0.000000   
VERB    0.000000  0.000000    0.000000  0.000000  0.000000  0.000000   
NOUN    0.000044  0.000218    0.000000  0.000000  0.000044  0.000218   
ADV     0.000000  0.000000    0.000000  0.000000  0.000000  0.000000   
NUM     0.000000  0.000000    0.000000  0.000000  0.000000  0.000000   
CONJ    0.000000  0.000000    0.000000  0.000000  0.000000  0.000000   
ADJ     0.000000  0.000000    0.000194  0.003301  0.000000  0.000000   
ADP     0.000000  0.000000    0.000000  0.000000  0.000000  0.000000   
X       0.000000  0.000000    0.000000  0.000000  0.000000  0.000000   
PRON    0.000000  0.000000    0.000000  0.000000  0.000000  0.000000   
PRT     0.000000  0.000000    0.000000  0.000000  0.000000  0.000000   

      Services  intelligence  responses  short-term  ...  attac

In [ ]:
# compute Emission Probability
def word_given_tag(word, tag, B=B, encode_hs=encode_hs, encode_vs=encode_vs):
    # your code here
    if word not in encode_vs.keys():
        return 1
    else:
        # print(tag)
        # print(encode_vs[word])
        return B[encode_hs[tag], encode_vs[word]]



# compute Transition Probability
def t2_given_t1(t2, t1, train_bag = train_tagged_words, A=A, encode_hs=encode_hs):
    # your code here
    return A[t1,t2]


In [ ]:
def Viterbi(words, train_bag = train_tagged_words, encode_hs = encode_hs, pi = pi):
    # your code here

    t = len(words) #Number of Time steps

    #parents = np.zeros((t, len(encode_hs.keys())))
    parents = np.zeros((len(encode_hs.keys()), t)) #My way
    
    #We'll use two layers
    layer0 = pi.copy()
    layer1 = np.zeros(len(pi))

    #Setting up initial layer - time step 0
    for tag in encode_hs.keys():
        layer0[encode_hs[tag]] = layer0[encode_hs[tag]] * word_given_tag(words[0], tag)

    #Working on time steps 1 to t
    for i in range(1, t):
        word = words[i]
        #Working on each element
        for j in range(len(encode_hs.keys())):
            #Declaring a temporary variable
            x = np.zeros(len(encode_hs.keys()))
            #Calculating all possible combinations to jth hidden state
            for k in range(len(encode_hs.keys())):
                x[k] = layer0[k]*t2_given_t1(k,j) * word_given_tag(word, list(encode_hs.keys())[j])
            
            layer1[j] = x.max()

            parents[j, i] = x.argmax()

        
        layer0=layer1.copy()


    #Backtracking
    sequence = [layer0.argmax()]
    for i in range(1, t):
        sequence+=[int(parents[sequence[-1], -i])]
    
    sequence = sequence[::-1]
    return [decode_hs[state] for state in sequence]


In [ ]:
random.seed(1234)      # define a random seed to get same sentences when run multiple times

# choose random 10 numbers
rndom = [random.randint(1, len(test_set)) for x in range(10)]
# list of 10 sentences on which to test the model
test_run = [test_set[i] for i in rndom]

# testing 10 sentences to check the accuracy
t_seq = [] #sequence of all tags in each sentence - sentence wise

start = time.time()

for sentence in test_run:
    s=[tup[0] for tup in sentence]
    sequence = Viterbi(s)
    t_seq.append(sequence)
end = time.time()
difference = end - start
 
print("Time taken in seconds:", difference)

# list of tagged words
test_run_base = [tup for sent in test_run for tup in sent]

tagged_seq = []

for l in t_seq:
    tagged_seq += l

# accuracy should be good enough (> 90%) to be a satisfactory model
check = [i for i, j in zip(tagged_seq, test_run_base) if i == j[1]] 
 
accuracy = len(check) / len(tagged_seq)
print('Viterbi Algorithm Accuracy:', accuracy * 100)

Time taken in seconds: 0.14170169830322266
Viterbi Algorithm Accuracy: 93.30143540669856


# Toy Model

In [ ]:
#Going from Row to Column
A = np.array([
    #C,  H
    [0.5,0.5],#C
    [0.4,0.6]#H
])

B = np.array([
    # 1,  2,  3
    [0.5,0.4,0.1],#C
    [0.2,0.4,0.4]#H
])

In [ ]:
#C,H
pi = np.array([0.2,0.8])

In [ ]:
#             3, 1, 3
V = np.array([2,0,2])

## Brute Force

In [ ]:
#['CHH', 'CHC', 'CCH', 'CCC', 'HHH', 'HHC', 'HCH', 'HCC']
sequences = ['011', '010', '001', '000', '111', '110', '101', '100']

In [ ]:
v1=2
v2=0
v3=2

In [ ]:
d = {}
for k in sequences:
    s1=int(k[0])
    s2=int(k[1])
    s3=int(k[2])
    d[k]=pi[s1] * A[s1,s2] * A[s2,s3]*B[s1,v1] * B[s2,v2] * B[s3,v3]
print(d)

{'011': 0.00048000000000000007, '010': 8.000000000000003e-05, '001': 0.0010000000000000002, '000': 0.00025000000000000006, '111': 0.009216, '110': 0.0015360000000000003, '101': 0.012800000000000004, '100': 0.003200000000000001}


In [ ]:
#Probability of this observation
sum(d.values())

0.028562000000000008

In [ ]:
#Most Probable Hidden State Sequence
m = max(d.values())
for key, value in d.items():
    if value == m:
        print(key)

101


In [ ]:
def viterbi_toy(A, B, V):
    #Initializing Arrays
    t = len(V)
    parents = np.empty((A.shape[0], t))
    parents[:] = np.nan
    values = np.empty((A.shape[0], t))
    values[:] = np.nan

    hs = list(range(A.shape[0]))
    #Time step 1 - parents array doesn't need to be updated
    for j in hs:
        values[j,0] = pi[j] * B[j, V[0]]
    
    
    #Time step 2 to t - parents array needs to be updated
    for i in range(1,t):
        for j in hs:
            l = [values[k,i-1] * A[k,j] * B[j,V[i]] for k in hs]
            #Values[k, i-1] signifies the previous step node.
            #What this is doing is essentially calculating the probability of getting to the state j in time step i
            #from all the hidden nodes at time step i-1
            #and then outputting the given visible sequence node
            #We store the maximum of it
            values[j,i] = max(l)
            parents[j,i] = np.argmax(l)
    print("Parents: \n", parents)
    print("Values: \n", values)
    #Backtracking
    sequence = ""
    #Initial Step
    sequence += str(np.argmax(values[:,-1]))
    m = np.max(values[:,-1])
    #Appending other steps
    for i in range(1,t):
        sequence+=str(int(parents[int(sequence[-1]), -i]))
    
    sequence = sequence[::-1]

    return sequence, m
viterbi_toy(A,B,V)

Parents: 
 [[nan  1.  0.]
 [nan  1.  0.]]
Values: 
 [[0.02   0.064  0.0032]
 [0.32   0.0384 0.0128]]


('101', 0.012800000000000004)

In [ ]:
def forward(A, B, V):
    #Initializing Arrays
    t = len(V)
    values = np.empty((A.shape[0], t))
    values[:] = np.nan

    hs = list(range(A.shape[0]))
    #Time step 1 - initial probabilities
    for j in hs:
        values[j,0] = pi[j] * B[j, V[0]]
    
    
    #Time step 2 to t
    for i in range(1,t):
        for j in hs:
            l = [values[k,i-1] * A[k,j] * B[j,V[i]] for k in hs]
            #Values[k, i-1] signifies the previous step node.
            #What this is doing is essentially calculating the probability of getting to the state j in time step i
            #from all the hidden nodes at time step i-1
            #and then outputting the given visible sequence node
            #We store the maximum of it
            values[j,i] = sum(l)

    return sum(values[:,-1])
forward(A,B,V)

0.02856200000000001